### ISSUE TITLE
Release from 1.0.4 branch on pypi

### ISSUE THREAD

**Issue by Dobatymo** [adobe/libLOL#3]
Hi, the 1.0.4 branch seems to have many unexplained changes and some fixes from 0.1.0.3 undone (like the encoding param)

These broken releases are now on pypi https://pypi.org/project/lolc/ (which links to non-existing <https://github.com/adobe/lolc> by the way)

**Comment by tiberiu44** [comment]
@Dobatymo - thank you for letting us know about this. You are right, there have been major changes that are not completely documented, but I don't know how the previous updates slipped. We we have this fixed on Github soon and in the next package release.

**Comment by tiberiu44** [comment]
I merged the branches and tested the new release and uploaded to pypi (0.1.0.6). I hope to have fixed all major issues. If you spot anything else, let me know.
